version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12

    steps:
      - checkout

      - run:
          name: Lint the markdown
          command: |
            make lint

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
